import { redirect } from "next/navigation";
import { AlertCircle, ArrowRight, Bell, CalendarDays, CheckCircle2, CreditCard, LogOut, Shirt, TrendingUp, Users } from "lucide-react";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getStripe } from "@/lib/stripe/server";
import { signOut } from "@/app/login/actions";

const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD"});
const date=(value:string|number)=>new Date(typeof value==="number"?value*1000:value).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
type ParentChild={id:string;first_name:string;last_name:string;grade:string|null;jersey:string|null;team_id:string|null;teams:{name?:string}|Array<{name?:string}>|null};

export default async function ParentPortal(){
 const supabase=await createSupabaseServerClient();
 const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data:account}=await supabase.from("parent_accounts").select("full_name").eq("user_id",user.id).maybeSingle();if(!account)redirect("/");
 const{data:links}=await supabase.from("parent_player_links").select("relationship, players(id,first_name,last_name,grade,jersey,team_id,teams(name))").eq("parent_user_id",user.id);
 const children:ParentChild[]=(links??[]).flatMap(link=>{const raw=link.players as unknown as ParentChild|ParentChild[]|null;const player=Array.isArray(raw)?raw[0]:raw;return player?[player]:[]});
 const playerIds=children.map(player=>String(player.id)),teamIds=[...new Set(children.map(player=>String(player.team_id??"")).filter(Boolean))];
 const[{data:billing},{data:events},{data:announcements},{data:jerseys},{data:notes},{data:invoiceLinks}]=await Promise.all([
  playerIds.length?supabase.from("player_billing").select("player_id,monthly_tuition,open_balance,billing_status,stripe_customer_id").in("player_id",playerIds):Promise.resolve({data:[]}),
  teamIds.length?supabase.from("team_events").select("id,team_id,title,event_type,opponent,location,start_at,arrival_minutes,status").in("team_id",teamIds).gte("start_at",new Date().toISOString()).order("start_at").limit(30):Promise.resolve({data:[]}),
  supabase.from("team_announcements").select("id,team_id,title,message,priority,created_at").eq("is_active",true).order("created_at",{ascending:false}).limit(20),
  playerIds.length?supabase.from("player_jersey_tracking").select("player_id,jersey_number,jersey_size,status").in("player_id",playerIds):Promise.resolve({data:[]}),
  playerIds.length?supabase.from("player_development_notes").select("id,player_id,category,note,activity_date,created_at").in("player_id",playerIds).eq("parent_visible",true).order("created_at",{ascending:false}).limit(30):Promise.resolve({data:[]}),
  playerIds.length?supabase.from("stripe_invoice_links").select("stripe_invoice_id,player_id,category,description,due_date").in("player_id",playerIds):Promise.resolve({data:[]})
 ]);
 const invoices:Array<{id:string;playerId:string;category:string;description:string|null;number:string;status:string;amountDue:number;amountPaid:number;remaining:number;created:number;due:number|null;url:string|null;pdf:string|null}>=[];
 try{const stripe=getStripe();for(const row of billing??[]){if(!row.stripe_customer_id)continue;const result=await stripe.invoices.list({customer:row.stripe_customer_id,limit:100});for(const invoice of result.data)if(invoice.id&&!invoices.some(item=>item.id===invoice.id)){const linked=invoiceLinks?.find(item=>item.stripe_invoice_id===invoice.id);invoices.push({id:invoice.id,playerId:linked?.player_id??row.player_id,category:linked?.category??"tuition",description:linked?.description??invoice.description??null,number:invoice.number??invoice.id,status:invoice.status??"unknown",amountDue:invoice.amount_due/100,amountPaid:invoice.amount_paid/100,remaining:invoice.amount_remaining/100,created:invoice.created,due:invoice.due_date??null,url:invoice.hosted_invoice_url??null,pdf:invoice.invoice_pdf??null})}}}catch{}
 invoices.sort((a,b)=>b.created-a.created);const open=invoices.filter(invoice=>invoice.remaining>0),balance=open.reduce((sum,invoice)=>sum+invoice.remaining,0);
 const childName=(id:unknown)=>{const child=children.find(item=>item.id===id);return child?`${child.first_name} ${child.last_name}`:"Player"};
 const payable=open.find(invoice=>invoice.url),nextEvent=events?.[0],important=announcements?.find(item=>["urgent","important"].includes(item.priority));
 const pendingJerseys=(jerseys??[]).filter(item=>item.status!=="given_to_player");
 const actions=[
  ...(payable?[{kind:"payment",title:`Pay ${money(balance)}`,detail:`${open.length} open invoice${open.length===1?"":"s"}`,href:payable.url??"#billing",external:Boolean(payable.url)}]:[]),
  ...(important?[{kind:"alert",title:important.title,detail:"Important club announcement",href:"#announcements",external:false}]:[]),
  ...(pendingJerseys.length?[{kind:"jersey",title:`${pendingJerseys.length} jersey update${pendingJerseys.length===1?"":"s"}`,detail:"Check your family’s uniform status",href:"#family",external:false}]:[]),
  ...(nextEvent?[{kind:"event",title:nextEvent.title,detail:`${date(nextEvent.start_at)}${nextEvent.location?` · ${nextEvent.location}`:""}`,href:"#schedule",external:false}]:[])
 ];
 return <main className="parent-shell"><header className="parent-header"><div className="brand"><div className="brand-mark">I</div><div><strong>INVICTUS</strong><span>Family Portal</span></div></div><div><span>{account.full_name}</span><form action={signOut}><button><LogOut size={15}/> Sign out</button></form></div></header><div className="parent-content">
  <section className="parent-welcome"><p className="eyebrow">Family dashboard</p><h1>Everything your family needs, in one place.</h1><p>Payments, schedules, announcements, and player updates for {children.length===1?"your player":"your players"}.</p></section>
  <section className="parent-actions"><div className="parent-title"><AlertCircle/><div><p className="eyebrow">Action center</p><h2>What needs your attention</h2></div></div>{actions.length?<div className="parent-action-grid">{actions.map((action,index)=><a key={`${action.kind}-${index}`} className={`parent-action ${action.kind}`} href={action.href} target={action.external?"_blank":undefined}><div><strong>{action.title}</strong><span>{action.detail}</span></div><ArrowRight/></a>)}</div>:<div className="parent-all-clear"><CheckCircle2/><div><strong>You’re all caught up.</strong><span>No payments or family tasks need attention right now.</span></div></div>}</section>
  <section className="parent-summary"><article className={balance>0?"needs-payment":"paid-up"}><CreditCard/><span>Amount currently due</span><strong>{money(balance)}</strong><small>{open.length?`${open.length} open invoice${open.length===1?"":"s"}`:"Your account is paid up"}</small></article><article><Users/><span>Players</span><strong>{children.length}</strong><small>{children.map(child=>`${child.first_name} ${child.last_name}`).join(" · ")}</small></article><article><CalendarDays/><span>Upcoming events</span><strong>{events?.length??0}</strong><small>Across your family’s teams</small></article></section>
  <section className="parent-grid"><article id="billing" className="parent-card parent-invoices"><div className="parent-title"><CreditCard/><div><p className="eyebrow">Family billing</p><h2>Invoices by player</h2></div></div>{invoices.length?<div className="family-billing-groups">{children.map(child=>{const childInvoices=invoices.filter(invoice=>invoice.playerId===child.id),childDue=childInvoices.reduce((sum,invoice)=>sum+invoice.remaining,0);return <section className="family-billing-group" key={child.id}><header><div><strong>{child.first_name} {child.last_name}</strong><span>{childInvoices.length} invoice{childInvoices.length===1?"":"s"}</span></div><div><small>Currently due</small><b>{money(childDue)}</b></div></header>{childInvoices.length?childInvoices.map(invoice=><div className="parent-invoice" key={invoice.id}><div><span className={`invoice-category ${invoice.category}`}>{invoice.category}</span><strong>{invoice.description||`Invoice ${invoice.number}`}</strong><span>{date(invoice.created)} · {invoice.status.replaceAll("_"," ")}{invoice.due?` · Due ${date(invoice.due)}`:""}</span></div><div><b>{money(invoice.amountDue)}</b><small>{invoice.remaining>0?`${money(invoice.remaining)} due`:`${money(invoice.amountPaid)} paid`}</small></div>{invoice.remaining>0&&invoice.url?<a href={invoice.url} target="_blank">Pay now</a>:invoice.pdf?<a href={invoice.pdf} target="_blank">Receipt</a>:null}</div>):<p className="parent-empty">No invoices are linked to this player.</p>}</section>})}</div>:<p className="parent-empty">No Stripe invoices are linked yet.</p>}</article>
   <article id="announcements" className="parent-card"><div className="parent-title"><Bell/><div><p className="eyebrow">Club updates</p><h2>Announcements</h2></div></div>{announcements?.length?announcements.map(item=><div className={`parent-announcement ${item.priority}`} key={item.id}><strong>{item.title}</strong><p>{item.message}</p><small>{date(item.created_at)}</small></div>):<p className="parent-empty">No current announcements.</p>}</article>
   <article id="schedule" className="parent-card"><div className="parent-title"><CalendarDays/><div><p className="eyebrow">Schedule</p><h2>Coming up</h2></div></div>{events?.length?events.map(item=><div className="parent-event" key={item.id}><time>{new Date(item.start_at).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}<b>{new Date(item.start_at).toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"})}</b></time><div><strong>{item.title}</strong><span>{[item.opponent,item.location].filter(Boolean).join(" · ")||item.event_type}</span>{item.arrival_minutes?<small>Arrive {item.arrival_minutes} minutes early</small>:null}</div></div>):<p className="parent-empty">No upcoming team events.</p>}</article>
   <article className="parent-card"><div className="parent-title"><TrendingUp/><div><p className="eyebrow">Player updates</p><h2>From the coaches</h2></div></div>{notes?.length?notes.map(item=><div className="parent-note" key={item.id}><div><strong>{childName(item.player_id)}</strong><span>{item.category.replaceAll("_"," ")}</span></div><p>{item.note}</p><small>{date(item.activity_date??item.created_at)}</small></div>):<p className="parent-empty">No coach updates have been shared yet.</p>}</article>
   <article id="family" className="parent-card parent-players"><div className="parent-title"><Shirt/><div><p className="eyebrow">Players</p><h2>Your family</h2></div></div>{children.map(child=>{const teamRaw=child.teams as unknown as {name?:string}|Array<{name?:string}>|null,team=Array.isArray(teamRaw)?teamRaw[0]:teamRaw,jersey=jerseys?.find(item=>item.player_id===child.id),bill=billing?.find(item=>item.player_id===child.id);return <div key={String(child.id)}><div className="coach-avatar">{String(child.first_name)[0]}{String(child.last_name)[0]}</div><div><strong>{String(child.first_name)} {String(child.last_name)}</strong><span>{team?.name??"Team not assigned"} · {child.grade??"Grade not set"}</span><small>{jersey?`Jersey ${jersey.jersey_number??""} · ${jersey.status.replaceAll("_"," ")}`:"Jersey status not available"}</small></div><b className={bill?.billing_status==="active"?"paid":"due"}>{bill?.billing_status?.replaceAll("_"," ")??"Not linked"}</b></div>})}</article>
  </section>
 </div></main>;
}
