import{NextResponse}from"next/server";import{createSupabaseServerClient}from"@/lib/supabase/server";const text=(b:Record<string,unknown>,k:string)=>String(b[k]??"").trim();
export async function POST(request:Request){try{const body=await request.json() as Record<string,unknown>,supabase=await createSupabaseServerClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in again.");const{data:profile}=await supabase.from("profiles").select("role, coach_id").eq("id",user.id).single();const manager=["owner_admin","program_director"].includes(profile?.role??""),action=text(body,"action");
if(action==="request_session"){if(!profile?.coach_id)throw new Error("Your login is not linked to a coach profile yet. Ask Molly or an owner to link it.");const slotId=text(body,"slotId");const{data:slot}=await supabase.from("court_slots").select("id,status,slot_type").eq("id",slotId).single();if(!slot||slot.status!=="open"||slot.slot_type!=="open_pt")throw new Error("That PT time is no longer available.");const{error}=await supabase.from("pt_session_requests").insert({slot_id:slotId,coach_id:profile.coach_id,requested_by:user.id,client_name:text(body,"clientName")||null,notes:text(body,"notes")||null});if(error)throw error;await supabase.from("court_slots").update({status:"held"}).eq("id",slotId).eq("status","open");return NextResponse.json({ok:true})}
if(!manager)throw new Error("Schedule manager access required.");
if(action==="create_court"){const name=text(body,"name");if(!name)throw new Error("Court name is required.");const{error}=await supabase.from("courts").insert({name});if(error)throw error;return NextResponse.json({ok:true})}
if(action==="create_slot"){const courtId=text(body,"courtId"),slotType=text(body,"slotType"),startAt=text(body,"startAt"),endAt=text(body,"endAt");if(!courtId||!startAt||!endAt)throw new Error("Court, start, and end are required.");if(!["open_pt","class","blocked"].includes(slotType))throw new Error("Choose a valid time type.");const{error}=await supabase.from("court_slots").insert({court_id:courtId,start_at:new Date(startAt).toISOString(),end_at:new Date(endAt).toISOString(),slot_type:slotType,title:text(body,"title")||null,status:slotType==="open_pt"?"open":"booked",created_by:user.id});if(error)throw error;return NextResponse.json({ok:true})}
if(action==="link_coach"){const{error}=await supabase.from("profiles").update({coach_id:text(body,"coachId")||null}).eq("id",text(body,"profileId"));if(error)throw error;return NextResponse.json({ok:true})}
if(action==="update_request"){const requestId=text(body,"requestId"),status=text(body,"status");if(!["approved","declined","completed","cancelled"].includes(status))throw new Error("Choose a valid request status.");const{data:requestRow,error}=await supabase.from("pt_session_requests").update({status,updated_at:new Date().toISOString()}).eq("id",requestId).select("slot_id").single();if(error)throw error;await supabase.from("court_slots").update({status:["approved","completed"].includes(status)?"booked":"open"}).eq("id",requestRow.slot_id);return NextResponse.json({ok:true})}
if(action==="update_fee"){const feeStatus=text(body,"feeStatus"),method=text(body,"paymentMethod"),amount=Number(body.feeAmount??5);if(!["unpaid","paid","waived"].includes(feeStatus)||!Number.isFinite(amount)||amount<0)throw new Error("Choose a valid fee status and amount.");const{error}=await supabase.from("pt_session_requests").update({fee_amount:amount,fee_status:feeStatus,payment_method:feeStatus==="paid"?(method||"other"):null,updated_at:new Date().toISOString()}).eq("id",text(body,"requestId"));if(error)throw error;return NextResponse.json({ok:true})}throw new Error("Unknown schedule action.")}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to update schedule."},{status:400})}}
