import Link from "next/link";
import { AlertCircle, BadgeDollarSign, CalendarClock, ChevronRight, Clock3, Plane, WalletCards } from "lucide-react";

type Collection={playerId:string;name:string;team:string|null;amount:number;status:string};
type TimeEntry={id:string;coachName:string;workDate:string;hours:number;status:string};
type PtItem={id:string;coachName:string;clientName:string;status:string;feeAmount:number;feeStatus:string;startAt:string};
type Followup={id:string;teamName:string;note:string;activityDate:string;createdAt:string;resolvedAt:string;followUpNeeded:boolean;category?:string};
type TravelItem={trip:string;player:string;balance:number;deadline:string};
type Facility={id:string;name:string;status:string;priority:string;estimatedCost:number};
type SeasonItem={playerId:string;name:string;teamName:string;registrationForm:boolean;waiver:boolean;emergencyMedical:boolean;proofOfAge:boolean};
type JerseyItem={playerId:string;name:string;teamName:string;status:string};
type Props={name:string;showFinancials:boolean;cashBalance:number;expectedTuition:number;payrollTotal:number;plannedExpenses:number;otherRevenue:number;safetyCushion:number;safeCash:number;planReady:boolean;collections:Collection[];timeEntries:TimeEntry[];ptItems:PtItem[];playerFollowups:Followup[];travelItems:TravelItem[];facilities:Facility[];seasonItems:SeasonItem[];jerseyItems:JerseyItem[]};
const money=(n:number)=>n.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const date=(s:string)=>s?new Date(`${s.slice(0,10)}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"}):"No date";

export function AdminOverview(p:Props){
 const pendingTime=p.timeEntries.filter(x=>x.status==="submitted"),pendingPt=p.ptItems.filter(x=>x.status==="requested"),missing=p.seasonItems.filter(x=>!x.registrationForm||!x.waiver||!x.emergencyMedical||!x.proofOfAge),jerseys=p.jerseyItems.filter(x=>x.status!=="given_to_player");
 const collect=p.collections.reduce((s,x)=>s+x.amount,0),travel=p.travelItems.reduce((s,x)=>s+x.balance,0),projected=p.cashBalance+p.expectedTuition+p.otherRevenue-p.plannedExpenses;
 if(!p.showFinancials)return <div className="admin-home"><section className="admin-welcome"><div><p className="eyebrow">Today at Invictus</p><h2>Welcome, {p.name.split(" ")[0]}.</h2><p>Handle the important items first, then get back to basketball.</p></div><BadgeDollarSign/></section><section className="admin-kpis"><Link href="/?view=readiness"><span>Missing paperwork</span><strong>{missing.length}</strong><small>Players not fully cleared</small></Link><Link href="/?view=jerseys"><span>Jerseys outstanding</span><strong>{jerseys.length}</strong><small>Not given to players</small></Link><Link href="/?view=time"><span>Coach hours waiting</span><strong>{pendingTime.length}</strong><small>Entries to review</small></Link><Link href="/?view=schedule"><span>PT requests</span><strong>{pendingPt.length}</strong><small>Waiting for approval</small></Link></section></div>;
 return <div className="admin-home finance-control">
  <section className="finance-command"><div><p className="eyebrow">Private finance control center</p><h2>Can we cover the bills—and what needs attention?</h2><p>Cash, collections, payroll, and travel money in one clear place.</p></div><WalletCards/></section>
  <section className="finance-primary-kpis"><Link href="/?view=cash"><span>Money in the bank now</span><strong>{money(p.cashBalance)}</strong><small>Latest QuickBooks sync</small></Link><Link href="/?view=billing" className={p.collections.length?"attention":""}><span>Player money to collect</span><strong>{money(collect)}</strong><small>{p.collections.length} families need follow-up</small></Link><Link href="/?view=payroll"><span>Expected payroll</span><strong>{money(p.payrollTotal)}</strong><small>{pendingTime.length} time entries waiting</small></Link><Link href="/?view=cash" className={p.planReady?"safe":"incomplete"}><span>{p.planReady?"Safe extra cash":"Safe cash not ready"}</span><strong>{p.planReady?money(p.safeCash):"Finish the plan"}</strong><small>{p.planReady?"After bills and safety cushion":"Add bills and a bank cushion"}</small></Link></section>
  <section className="cash-bridge"><div className="admin-section-title"><div><BadgeDollarSign/><h3>This month&apos;s cash picture</h3></div><Link href="/?view=cash">Update plan <ChevronRight/></Link></div><div className="cash-bridge-flow"><div><span>Bank now</span><strong>{money(p.cashBalance)}</strong></div><b>+</b><div><span>Expected money in</span><strong>{money(p.expectedTuition+p.otherRevenue)}</strong></div><b>−</b><div><span>Planned bills</span><strong>{money(p.plannedExpenses)}</strong></div><b>=</b><div><span>Projected month end</span><strong>{money(projected)}</strong></div></div><p className={!p.planReady?"finance-warning":""}>{p.planReady?<>Keeping <b>{money(p.safetyCushion)}</b> untouched leaves about <b>{money(p.safeCash)}</b> for repairs or other priorities.</>:"Complete this month’s bills and minimum bank cushion before treating the balance as extra money."}</p></section>
  <div className="admin-action-grid finance-action-grid"><section><div className="admin-section-title"><div><AlertCircle/><h3>Collections to handle</h3></div><Link href="/?view=billing">Billing <ChevronRight/></Link></div><div className="admin-collection-list">{p.collections.slice(0,6).map(x=><Link href="/?view=billing" key={x.playerId}><div><strong>{x.name}</strong><span>{x.team??"No team"} · {x.status.replaceAll("_"," ")}</span></div><b>{money(x.amount)}</b></Link>)}{!p.collections.length?<p className="admin-clear">No player balances need follow-up.</p>:null}</div></section><section><div className="admin-section-title"><div><Plane/><h3>Travel money at risk</h3></div><Link href="/?view=travel">Travel <ChevronRight/></Link></div><div className="finance-section-total"><span>Still owed for trips</span><strong>{money(travel)}</strong></div><div className="admin-collection-list">{p.travelItems.slice(0,5).map((x,i)=><Link href="/?view=travel" key={i}><div><strong>{x.player}</strong><span>{x.trip} · due {date(x.deadline)}</span></div><b>{money(x.balance)}</b></Link>)}{!p.travelItems.length?<p className="admin-clear">No travel balances need attention.</p>:null}</div></section><section><div className="admin-section-title"><div><Clock3/><h3>Payroll check</h3></div><Link href="/?view=payroll">Payroll <ChevronRight/></Link></div><div className="finance-section-total"><span>Current payroll plan</span><strong>{money(p.payrollTotal)}</strong></div><div className="admin-action-list">{pendingTime.slice(0,5).map(x=><Link href="/?view=time" key={x.id}><Clock3/><div><strong>Review {x.coachName}&apos;s hours</strong><span>{x.hours.toFixed(2)} hours · {date(x.workDate)}</span></div><ChevronRight/></Link>)}{!pendingTime.length?<p className="admin-clear">No coach hours are waiting.</p>:null}</div></section><section><div className="admin-section-title"><div><CalendarClock/><h3>Money decisions</h3></div></div><div className="finance-shortcuts">{[["cash","Monthly cash plan","Enter bills and see what is safe"],["facility","Facility budget",`${p.facilities.filter(x=>x.status!=="completed").length} open projects`],["pricing","Tuition pricing","Test a price before changing it"],["quickbooks","QuickBooks","Refresh the bank balance"]].map(x=><Link href={`/?view=${x[0]}`} key={x[0]}><span>{x[1]}</span><small>{x[2]}</small><ChevronRight/></Link>)}</div></section></div>
 </div>;
}
