import Link from "next/link";
import { AlertCircle, BadgeDollarSign, CalendarClock, ChevronRight, Clock3, ClipboardCheck, Hammer, Plane, Shirt, Users } from "lucide-react";

type Collection={playerId:string;name:string;team:string|null;amount:number;status:string};
type TimeEntry={id:string;coachName:string;workDate:string;hours:number;status:string};
type PtItem={id:string;coachName:string;clientName:string;status:string;feeAmount:number;feeStatus:string;startAt:string};
type Followup={id:string;teamName:string;note:string;activityDate:string;createdAt:string;resolvedAt:string;followUpNeeded:boolean;category?:string;contactMethod?:string;contactOutcome?:string};
type TravelItem={trip:string;player:string;balance:number;deadline:string};
type Facility={id:string;name:string;status:string;priority:string;estimatedCost:number};
type SeasonItem={playerId:string;name:string;teamName:string;registrationForm:boolean;waiver:boolean;emergencyMedical:boolean;proofOfAge:boolean};
type JerseyItem={playerId:string;name:string;teamName:string;status:string};
type Props={name:string;showFinancials:boolean;cashBalance:number;expectedTuition:number;collections:Collection[];timeEntries:TimeEntry[];ptItems:PtItem[];playerFollowups:Followup[];travelItems:TravelItem[];facilities:Facility[];seasonItems:SeasonItem[];jerseyItems:JerseyItem[]};
const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const date=(value:string)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"}):"No date";

export function AdminOverview({name,showFinancials,cashBalance,expectedTuition,collections,timeEntries,ptItems,playerFollowups,travelItems,facilities,seasonItems,jerseyItems}:Props){
  const pendingTime=timeEntries.filter(entry=>entry.status==="submitted"),pendingPt=ptItems.filter(item=>item.status==="requested"),unpaidPt=ptItems.filter(item=>item.feeStatus==="unpaid"&&["approved","completed"].includes(item.status)),openFollowups=playerFollowups.filter(item=>item.followUpNeeded&&!item.resolvedAt),parentFollowups=openFollowups.filter(item=>["parent_contact","payment_discussion","behavior"].includes(item.category??"")),otherFollowups=openFollowups.filter(item=>!["parent_contact","payment_discussion","behavior"].includes(item.category??"")),openFacilities=facilities.filter(item=>item.status!=="completed"),missingSeason=seasonItems.filter(item=>!item.registrationForm||!item.waiver||!item.emergencyMedical||!item.proofOfAge),outstandingJerseys=jerseyItems.filter(item=>item.status!=="given_to_player");
  const collectionTotal=collections.reduce((sum,item)=>sum+item.amount,0),travelTotal=travelItems.reduce((sum,item)=>sum+item.balance,0);
  const noActions=!missingSeason.length&&!outstandingJerseys.length&&!pendingTime.length&&!pendingPt.length&&!openFollowups.length;
  return <div className="admin-home"><section className="admin-welcome"><div><p className="eyebrow">Today at Invictus</p><h2>Welcome, {name.split(" ")[0]}.</h2><p>Handle the important items first, then get back to basketball.</p></div><BadgeDollarSign/></section>
    <section className="admin-kpis">{showFinancials?<><Link href="/?view=cash"><span>Money in the bank</span><strong>{money(cashBalance)}</strong><small>Latest QuickBooks sync</small></Link><Link href="/?view=billing" className={collections.length?"attention":""}><span>Player money to collect</span><strong>{money(collectionTotal)}</strong><small>{collections.length} players need attention</small></Link><Link href="/?view=travel" className={travelItems.length?"attention":""}><span>Travel money outstanding</span><strong>{money(travelTotal)}</strong><small>{travelItems.length} unpaid travelers</small></Link><Link href="/?view=cash"><span>Expected player payments</span><strong>{money(expectedTuition)}</strong><small>Active Stripe-linked tuition</small></Link></>:null}<Link href="/?view=readiness" className={missingSeason.length?"attention":""}><span>Missing season paperwork</span><strong>{missingSeason.length}</strong><small>Players not fully cleared</small></Link><Link href="/?view=jerseys" className={outstandingJerseys.length?"attention":""}><span>Jerseys outstanding</span><strong>{outstandingJerseys.length}</strong><small>Not yet given to players</small></Link><Link href="/?view=time" className={pendingTime.length?"attention":""}><span>Coach hours waiting</span><strong>{pendingTime.length}</strong><small>{pendingTime.reduce((sum,item)=>sum+item.hours,0).toFixed(2)} hours to review</small></Link><Link href="/?view=schedule" className={pendingPt.length?"attention":""}><span>PT requests waiting</span><strong>{pendingPt.length}</strong><small>{unpaidPt.length} unpaid PT fees</small></Link><Link href="/?view=players" className={openFollowups.length?"attention":""}><span>Player follow-ups</span><strong>{openFollowups.length}</strong><small>Coach concerns needing action</small></Link>{showFinancials?<Link href="/?view=facility"><span>Facility projects</span><strong>{openFacilities.length}</strong><small>Open repair and improvement items</small></Link>:null}</section>
    <div className="admin-action-grid"><section><div className="admin-section-title"><div><AlertCircle/><h3>Needs action</h3></div></div><div className="admin-action-list">{parentFollowups.slice(0,3).map(item=><Link href="/?view=players" key={item.id}><Users/><div><strong>Parent follow-up · {item.teamName||"Team"}</strong><span>{item.contactMethod?`${item.contactMethod.replaceAll("_"," ")} · `:""}{item.note}</span></div><ChevronRight/></Link>)}{missingSeason.slice(0,2).map(item=><Link href="/?view=readiness" key={`season-${item.playerId}`}><ClipboardCheck/><div><strong>Missing paperwork for {item.name}</strong><span>{item.teamName}</span></div><ChevronRight/></Link>)}{outstandingJerseys.slice(0,2).map(item=><Link href="/?view=jerseys" key={`jersey-${item.playerId}`}><Shirt/><div><strong>Jersey: {item.name}</strong><span>{item.teamName} · {item.status.replaceAll("_"," ")}</span></div><ChevronRight/></Link>)}{pendingTime.slice(0,2).map(item=><Link href="/?view=time" key={item.id}><Clock3/><div><strong>Approve {item.coachName}&apos;s hours</strong><span>{item.hours.toFixed(2)} hours · {date(item.workDate)}</span></div><ChevronRight/></Link>)}{pendingPt.slice(0,2).map(item=><Link href="/?view=schedule" key={item.id}><CalendarClock/><div><strong>PT request from {item.coachName}</strong><span>{item.clientName||"Client not entered"} · {date(item.startAt)}</span></div><ChevronRight/></Link>)}{otherFollowups.slice(0,2).map(item=><Link href="/?view=players" key={item.id}><Users/><div><strong>Player follow-up · {item.teamName||"Team"}</strong><span>{item.note}</span></div><ChevronRight/></Link>)}{noActions?<p className="admin-clear">No operational approvals or player follow-ups are waiting.</p>:null}</div></section>
      {showFinancials?<section><div className="admin-section-title"><div><BadgeDollarSign/><h3>Money to collect</h3></div><Link href="/?view=billing">Billing <ChevronRight/></Link></div><div className="admin-collection-list">{collections.slice(0,5).map(item=><Link href="/?view=billing" key={item.playerId}><div><strong>{item.name}</strong><span>{item.team??"No team"} · {item.status.replaceAll("_"," ")}</span></div><b>{money(item.amount)}</b></Link>)}{!collections.length?<p className="admin-clear">No player balances currently need follow-up.</p>:null}</div></section>:<section><div className="admin-section-title"><div><CalendarClock/><h3>Scheduling</h3></div><Link href="/?view=schedule">Open <ChevronRight/></Link></div><div className="admin-mini-stats"><div><span>PT requests</span><strong>{pendingPt.length}</strong></div><div><span>Unpaid PT fees</span><strong>{unpaidPt.length}</strong></div></div></section>}
      {showFinancials?<section><div className="admin-section-title"><div><Plane/><h3>Travel collections</h3></div><Link href="/?view=travel">Travel <ChevronRight/></Link></div><div className="admin-collection-list">{travelItems.slice(0,5).map((item,index)=><Link href="/?view=travel" key={`${item.trip}-${item.player}-${index}`}><div><strong>{item.player}</strong><span>{item.trip} · due {date(item.deadline)}</span></div><b>{money(item.balance)}</b></Link>)}{!travelItems.length?<p className="admin-clear">No travel balances need attention.</p>:null}</div></section>:null}
      {showFinancials?<section><div className="admin-section-title"><div><Hammer/><h3>Facility priorities</h3></div><Link href="/?view=facility">Projects <ChevronRight/></Link></div><div className="admin-collection-list">{openFacilities.slice(0,5).map(item=><Link href="/?view=facility" key={item.id}><div><strong>{item.name}</strong><span>{item.priority} · {item.status.replaceAll("_"," ")}</span></div><b>{money(item.estimatedCost)}</b></Link>)}{!openFacilities.length?<p className="admin-clear">No open facility projects.</p>:null}</div></section>:null}
    </div>
  </div>
}
