"use client";
import { useState } from "react";
import { Check, Clock3, X } from "lucide-react";

export type CoachTimeEntry={id:string;coachName:string;teamName:string;workDate:string;category:string;hours:number;notes:string;status:string};
type TeamOption={id:string;name:string};
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export function CoachTimeTracker({initialEntries,teams,canManage,coachLinked}:{initialEntries:CoachTimeEntry[];teams:TeamOption[];canManage:boolean;coachLinked:boolean}){
  const [message,setMessage]=useState(""),[saving,setSaving]=useState("");
  const pending=initialEntries.filter(entry=>entry.status==="submitted"),approvedHours=initialEntries.filter(entry=>entry.status==="approved").reduce((sum,entry)=>sum+entry.hours,0);
  async function submit(action:string,payload:Record<string,unknown>,key:string){setSaving(key);setMessage("");const response=await fetch("/api/coach-time",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const body=await response.json();if(response.ok){setMessage("Saved. Refreshing...");window.location.reload()}else{setMessage(body.error??"Unable to save.");setSaving("")}}
  return <section className="time-tracker"><div className="roster-heading"><div><p className="eyebrow">Coach time</p><h2 className="court-title"><Clock3 aria-hidden="true"/>{canManage?"Review coach hours":"Track my hours"}</h2><p className="muted">Coaches record their work here. Approved hours become the verified record for payroll.</p></div></div>
    <div className="time-summary"><div><span>{canManage?"Waiting for review":"Submitted entries"}</span><strong>{pending.length}</strong></div><div><span>Approved hours this month</span><strong>{approvedHours.toFixed(2)}</strong></div></div>
    {!canManage?<form className="time-entry-form" onSubmit={event=>{event.preventDefault();submit("add_entry",Object.fromEntries(new FormData(event.currentTarget).entries()),"new")}}><h3>Add time</h3>{coachLinked?<><label>Date<input name="workDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Work type<select name="category"><option value="team">Team practice / game</option><option value="skills">Skills class</option><option value="pt">Private training</option><option value="admin">Admin work</option><option value="other">Other</option></select></label><label>Team<select name="teamId"><option value="">No team / general</option>{teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>Hours<input name="hours" type="number" min="0.25" max="24" step="0.25" placeholder="1.5" required/></label><label className="time-notes">Note<input name="notes" placeholder="Practice, game, skills session..."/></label><button disabled={saving==="new"}>{saving==="new"?"Submitting...":"Submit hours"}</button></>:<p>Your login must be linked to your coach record before entering time.</p>}</form>:null}
    <div className="time-entry-list"><div className="time-entry-head"><span>Coach</span><span>Date / team</span><span>Work</span><span>Hours</span><span>Status</span></div>{initialEntries.map(entry=><article key={entry.id}><div><strong>{entry.coachName}</strong></div><div><strong>{new Date(`${entry.workDate}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</strong><span>{entry.teamName||"General"}</span></div><div><strong>{label(entry.category)}</strong><span>{entry.notes||"No note"}</span></div><strong>{entry.hours.toFixed(2)}</strong><div><span className={`time-status status-${entry.status}`}>{label(entry.status)}</span>{canManage&&entry.status==="submitted"?<div className="time-review"><button disabled={saving===entry.id} onClick={()=>submit("review_entry",{entryId:entry.id,status:"approved"},entry.id)}><Check size={13}/> Approve</button><button disabled={saving===entry.id} onClick={()=>submit("review_entry",{entryId:entry.id,status:"rejected"},entry.id)}><X size={13}/> Reject</button></div>:null}</div></article>)}</div>
    {!initialEntries.length?<p className="clearance-empty">No time has been entered for this month.</p>:null}{message?<p className="plan-message">{message}</p>:null}
  </section>;
}
