"use client";
import{useMemo,useState}from"react";import{AlertCircle,Check,ClipboardList,Search,X}from"lucide-react";
export type DevelopmentPlayer={id:string;firstName:string;lastName:string;team:string|null;grade:string|null;jersey:string|null};
export type DevelopmentNote={id:string;playerId:string;coachName:string;teamName:string;category:string;attendanceStatus:string;note:string;followUpNeeded:boolean;resolvedAt:string;createdAt:string};
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
export function CoachPlayerDevelopment({players,notes,coachLinked,canManage}:{players:DevelopmentPlayer[];notes:DevelopmentNote[];coachLinked:boolean;canManage:boolean}){
 const[query,setQuery]=useState(""),[selectedId,setSelectedId]=useState<string|null>(null),[category,setCategory]=useState("development"),[saving,setSaving]=useState(""),[message,setMessage]=useState("");
 const filtered=useMemo(()=>players.filter(player=>`${player.firstName} ${player.lastName} ${player.team??""}`.toLowerCase().includes(query.toLowerCase())),[players,query]);const selected=players.find(player=>player.id===selectedId),playerNotes=notes.filter(note=>note.playerId===selectedId),followups=notes.filter(note=>note.followUpNeeded&&!note.resolvedAt);
 async function submit(action:string,payload:Record<string,unknown>,key:string){setSaving(key);setMessage("");const response=await fetch("/api/player-development",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const body=await response.json();if(response.ok){setMessage("Saved. Refreshing...");window.location.reload()}else{setMessage(body.error??"Unable to save.");setSaving("")}}
 return <section className="development-card"><div className="roster-heading"><div><p className="eyebrow">Player development</p><h2>{canManage?"Coach notes and follow-ups":"My team development notes"}</h2><p className="muted">Track progress, attendance, and concerns without exposing billing or private owner information.</p></div><div className="development-followup-count"><AlertCircle size={17}/><strong>{followups.length}</strong><span>follow-ups</span></div></div><div className="roster-tools"><label><Search size={16}/><input placeholder="Search player or team" value={query} onChange={event=>setQuery(event.target.value)}/></label></div>
 <div className="development-player-grid">{filtered.map(player=><button key={player.id} onClick={()=>{setSelectedId(player.id);setMessage("")}}><strong>{player.firstName} {player.lastName}</strong><span>{player.team??"Unassigned"} · {[player.grade,player.jersey?`#${player.jersey}`:null].filter(Boolean).join(" · ")||"Player"}</span><small>{notes.filter(note=>note.playerId===player.id).length} notes</small></button>)}</div>
 {selected?<div className="development-panel"><div className="panel-title"><div><p className="eyebrow">Player record</p><h3>{selected.firstName} {selected.lastName}</h3><span>{selected.team}</span></div><button onClick={()=>setSelectedId(null)}><X/></button></div>{coachLinked?<form onSubmit={event=>{event.preventDefault();submit("add_note",{playerId:selected.id,...Object.fromEntries(new FormData(event.currentTarget).entries())},"note")}}><label>Category<select name="category" value={category} onChange={event=>setCategory(event.target.value)}><option value="development">Development goal</option><option value="strength">Strength / success</option><option value="improvement">Needs improvement</option><option value="attendance">Attendance</option><option value="behavior">Player / parent behavior</option><option value="general">General note</option></select></label>{category==="attendance"?<label>Attendance<select name="attendanceStatus"><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="excused">Excused</option></select></label>:null}<label className="development-note-field">Note<textarea name="note" placeholder="What happened, what is improving, or what needs attention?" required/></label><label className="followup-check"><input name="followUp" type="checkbox"/> Follow-up needed from Molly or an owner</label><button className="secondary" disabled={saving==="note"}><ClipboardList size={14}/> Add note</button></form>:<p className="clearance-empty">Your login must be linked to a coach record before adding notes.</p>}
 <div className="development-history"><h4>History</h4>{playerNotes.map(note=><article key={note.id} className={note.followUpNeeded&&!note.resolvedAt?"needs-followup":""}><div><span className={`note-category category-${note.category}`}>{label(note.category)}{note.attendanceStatus?` · ${label(note.attendanceStatus)}`:""}</span><strong>{note.coachName}</strong><small>{new Date(note.createdAt).toLocaleDateString()}</small></div><p>{note.note}</p>{note.followUpNeeded?<div className="note-followup">{note.resolvedAt?<span><Check size={13}/> Follow-up resolved</span>:canManage?<button onClick={()=>submit("resolve_note",{noteId:note.id},note.id)} disabled={saving===note.id}><Check size={13}/> Mark followed up</button>:<span><AlertCircle size={13}/> Follow-up requested</span>}</div>:null}</article>)}{!playerNotes.length?<p className="clearance-empty">No notes for this player yet.</p>:null}</div>{message?<p className="plan-message">{message}</p>:null}</div>:null}</section>
}
