"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Link2, Mail, Trash2 } from "lucide-react";
type Option={id:string;name:string}; type Link={parentUserId:string;parentName:string;playerId:string;playerName:string;relationship:string};
export function ParentAccessManager({logins,players,teams=[],links}:{logins:Option[];players:Option[];teams?:Option[];links:Link[]}){
 const router=useRouter(),[parentId,setParentId]=useState(""),[playerId,setPlayerId]=useState(""),[relationship,setRelationship]=useState("Parent / guardian"),[portalType,setPortalType]=useState<"parent"|"coach">("parent"),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[invitePlayer,setInvitePlayer]=useState(""),[teamId,setTeamId]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 async function send(payload:Record<string,unknown>){setSaving(true);setMessage("Saving access...");const response=await fetch("/api/parent/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();setMessage(response.ok?body.message??"Access updated.":body.error??"Unable to update access.");setSaving(false);if(response.ok){setEmail("");setFullName("");router.refresh()}}
 async function update(action:"link"|"unlink",pId=parentId,childId=playerId){const login=logins.find(item=>item.id===pId);await send({action,parentUserId:pId,playerId:childId,fullName:login?.name,relationship})}
 return <section className="parent-access-admin"><div className="roster-heading"><div><p className="eyebrow">Portal access</p><h2>Invite parents and coaches</h2><p className="muted">They receive a secure email and choose their own password.</p></div><Mail/></div><div className="portal-invite"><label>Portal type<select value={portalType} onChange={e=>setPortalType(e.target.value as "parent"|"coach")}><option value="parent">Parent</option><option value="coach">Coach</option></select></label><label>Full name<input value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{portalType==="parent"?<><label>Child<select value={invitePlayer} onChange={e=>setInvitePlayer(e.target.value)}><option value="">Choose player</option>{players.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Relationship<input value={relationship} onChange={e=>setRelationship(e.target.value)}/></label></>:<label>Initial team (optional)<select value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">Assign later</option>{teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<button disabled={saving||!fullName||!email||(portalType==="parent"&&!invitePlayer)} onClick={()=>send({action:"invite",portalType,fullName,email,playerId:invitePlayer,teamId,relationship})}>Send invitation</button></div><details className="existing-parent-links"><summary>Link an existing login to another child</summary><div className="parent-access-form"><label>Parent login<select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">Choose login</option>{logins.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Player<select value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Choose player</option>{players.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Relationship<input value={relationship} onChange={e=>setRelationship(e.target.value)}/></label><button onClick={()=>update("link")} disabled={saving||!parentId||!playerId}><Link2 size={14}/> Link portal</button></div></details>{message?<p className="plan-message">{message}</p>:null}<div className="parent-link-list">{links.length?links.map(link=><div key={`${link.parentUserId}-${link.playerId}`}><span><strong>{link.parentName}</strong><small>{link.relationship} of {link.playerName}</small></span><button title="Remove access" onClick={()=>update("unlink",link.parentUserId,link.playerId)} disabled={saving}><Trash2 size={15}/></button></div>):<p className="parent-empty">No parent logins are linked yet.</p>}</div></section>;
}
