"use client";
import {useMemo,useState} from"react";import{useRouter}from"next/navigation";import{Download,Upload,X}from"lucide-react";
type Team={id:string;name:string;season:string|null};type Row={firstName:string;lastName:string;teamId:string;teamName:string;grade:string;jersey:string;status:string;parentName:string;parentEmail:string;parentPhone:string;monthlyTuition:string;error?:string};
const columns=["first_name","last_name","team","grade","jersey","status","parent_name","parent_email","parent_phone","monthly_tuition"];
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(cell.trim());cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
export function PlayerImport({teams,existingNames}:{teams:Team[];existingNames:string[]}){const router=useRouter(),[open,setOpen]=useState(false),[rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);const existing=useMemo(()=>new Set(existingNames.map(n=>n.toLowerCase().trim())),[existingNames]);const valid=rows.filter(r=>!r.error);
function validate(row:Row,index:number,all:Row[]){const name=`${row.firstName} ${row.lastName}`.trim().toLowerCase();if(!row.firstName||!row.lastName)return"First and last name required";if(existing.has(name))return"Already in roster";if(all.some((r,i)=>i<index&&`${r.firstName} ${r.lastName}`.trim().toLowerCase()===name))return"Duplicate in file";if(row.teamName&&!row.teamId)return`Team “${row.teamName}” not found`;if(!["active","prospect","inactive"].includes(row.status))return"Invalid status";if(row.monthlyTuition&&(!Number.isFinite(Number(row.monthlyTuition))||Number(row.monthlyTuition)<0))return"Invalid tuition";return undefined}
async function load(file:File){setMessage("");const parsed=parseCsv(await file.text());if(parsed.length<2){setRows([]);setMessage("No player rows were found.");return}const heads=parsed[0].map(v=>v.toLowerCase().trim().replaceAll(" ","_"));const mapped=parsed.slice(1).map(values=>{const get=(key:string)=>values[heads.indexOf(key)]?.trim()??"",teamName=get("team"),team=teams.find(t=>t.name.toLowerCase()===teamName.toLowerCase());return{firstName:get("first_name"),lastName:get("last_name"),teamId:team?.id??"",teamName,grade:get("grade"),jersey:get("jersey"),status:(get("status")||"active").toLowerCase(),parentName:get("parent_name"),parentEmail:get("parent_email"),parentPhone:get("parent_phone"),monthlyTuition:get("monthly_tuition")}});setRows(mapped.map((r,i)=>({...r,error:validate(r,i,mapped)})))}
function template(){const csv=`${columns.join(",")}\nJordan,Sample,Example Team,7,12,active,Jamie Sample,parent@example.com,555-555-5555,150\n`,url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download="invictus-player-import.csv";a.click();URL.revokeObjectURL(url)}
async function submit(){setSaving(true);setMessage("Importing players...");const response=await fetch("/api/player-import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({players:valid})}),body=await response.json();if(response.ok){setRows([]);setMessage(`${body.imported} players imported successfully.`);router.refresh()}else setMessage(body.error??"Unable to import players.");setSaving(false)}
if(!open)return <button onClick={()=>setOpen(true)}><Upload size={15}/> Import roster</button>;return <div className="player-import-modal"><section className="player-import-panel"><div className="panel-title"><div><p className="eyebrow">New season setup</p><h3>Import the player roster</h3><p className="muted">Upload a CSV, review every row, then approve the import.</p></div><button onClick={()=>setOpen(false)} aria-label="Close import"><X/></button></div><div className="import-start"><button className="secondary" onClick={template}><Download size={15}/> Download template</button><label><Upload size={15}/> Choose completed CSV<input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void load(file)}}/></label></div>{rows.length?<><div className="import-summary"><strong>{rows.length}</strong> rows found <span>{valid.length} ready</span><span>{rows.length-valid.length} need attention</span></div><div className="table-wrap"><table className="import-table"><thead><tr><th>Player</th><th>Team</th><th>Grade / jersey</th><th>Parent</th><th>Tuition</th><th>Check</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className={r.error?"import-row-error":""}><td><strong>{r.firstName} {r.lastName}</strong><span>{r.status}</span></td><td>{r.teamName||"Unassigned"}</td><td>{[r.grade,r.jersey?`#${r.jersey}`:""].filter(Boolean).join(" · ")||"—"}</td><td>{r.parentName||"—"}<span>{r.parentEmail||r.parentPhone}</span></td><td>{r.monthlyTuition?`$${Number(r.monthlyTuition).toLocaleString()}`:"—"}</td><td>{r.error?<b>{r.error}</b>:<em>Ready</em>}</td></tr>)}</tbody></table></div><div className="import-actions"><button className="secondary" onClick={submit} disabled={saving||!valid.length}>{saving?"Importing...":`Import ${valid.length} players`}</button><button onClick={()=>setRows([])}>Clear file</button></div></>:<div className="import-empty">Use the template so names, teams, and tuition arrive in the correct columns. Existing players are flagged instead of duplicated.</div>}{message?<p className="plan-message">{message}</p>:null}</section></div>}
