"use client";
import{ChangeEvent,useMemo,useState}from"react";import{CalendarDays,Clock3,Download,FileUp,MapPin,Plus,Save,X}from"lucide-react";
export type TeamEvent={id:string;teamId:string;teamName:string;eventType:string;title:string;opponent:string;location:string;startAt:string;endAt:string;status:string;arrivalMinutes:number;notes:string};
type Team={id:string;name:string};type ImportRow=TeamEvent&{row:number;error:string};
const blank=(teamId:string):TeamEvent=>({id:"",teamId,teamName:"",eventType:"practice",title:"",opponent:"",location:"",startAt:"",endAt:"",status:"scheduled",arrivalMinutes:0,notes:""});
const local=(value:string)=>{if(!value)return"";const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const dateKey=(value:string)=>local(value).slice(0,10),day=(value:string)=>new Date(value).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"}),time=(value:string)=>new Date(value).toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(char==='"')quoted=!quoted;else if(char===","&&!quoted){row.push(cell.trim());cell=""}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&text[i+1]==="\n")i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=char}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
function download(name:string,content:string){const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([content],{type:"text/csv"}));link.download=name;link.click();URL.revokeObjectURL(link.href)}

export function TeamCalendar({initialEvents,teams,canManage}:{initialEvents:TeamEvent[];teams:Team[];canManage:boolean}){
  const[events]=useState(initialEvents),[team,setTeam]=useState("all"),[type,setType]=useState("all"),[editing,setEditing]=useState<TeamEvent|null>(null),[imports,setImports]=useState<ImportRow[]|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  const visible=useMemo(()=>events.filter(event=>(team==="all"||event.teamId===team)&&(type==="all"||event.eventType===type)),[events,team,type]);
  const grouped=[...new Map(visible.map(event=>[dateKey(event.startAt),visible.filter(item=>dateKey(item.startAt)===dateKey(event.startAt))])).entries()];
  function change(key:keyof TeamEvent,value:string|number){setEditing(current=>current?{...current,[key]:value}:current)}
  async function save(){if(!editing)return;setSaving(true);setMessage("");const response=await fetch("/api/team-calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing)}),body=await response.json();if(response.ok){setMessage("Event saved. Refreshing...");window.location.reload()}else{setMessage(body.error??"Unable to save event.");setSaving(false)}}
  async function readImport(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;const rows=parseCsv(await file.text()),headers=(rows.shift()??[]).map(value=>value.toLowerCase().replaceAll(" ","_")),value=(row:string[],name:string)=>row[headers.indexOf(name)]??"";const allowed=["practice","game","tournament","meeting","other"];setImports(rows.map((row,index)=>{const teamName=value(row,"team"),matched=teams.find(item=>item.name.toLowerCase()===teamName.toLowerCase()),eventType=value(row,"event_type").toLowerCase()||"practice",date=value(row,"date"),start=value(row,"start_time"),end=value(row,"end_time"),title=value(row,"title"),errors=[];if(!matched)errors.push(`Team “${teamName||"blank"}” was not found`);if(!date||!start)errors.push("Date and start time are required");if(!title)errors.push("Title is required");if(!allowed.includes(eventType))errors.push("Invalid event type");return{id:"",row:index+2,teamId:matched?.id??"",teamName,eventType,title,opponent:value(row,"opponent"),location:value(row,"location"),startAt:date&&start?`${date}T${start}`:"",endAt:date&&end?`${date}T${end}`:"",status:"scheduled",arrivalMinutes:Number(value(row,"arrival_minutes")||0),notes:value(row,"notes"),error:errors.join("; ")}}))}
  async function importAll(){if(!imports||imports.some(row=>row.error))return;setSaving(true);const response=await fetch("/api/team-calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({events:imports})}),body=await response.json();if(response.ok){setMessage(`${imports.length} calendar events imported.`);window.location.reload()}else{setMessage(body.error??"Unable to import schedule.");setSaving(false)}}
  const template=`team,event_type,title,date,start_time,end_time,location,opponent,arrival_minutes,notes\n${teams[0]?.name??"Team Name"},practice,Team Practice,2026-09-01,18:00,19:30,Invictus Court 1A,,10,Bring reversible jersey\n${teams[0]?.name??"Team Name"},game,League Game,2026-09-05,14:00,15:30,Main Gym,Rockets,30,White uniforms`;
  return <section className="team-calendar"><div className="roster-heading"><div><p className="eyebrow">Team calendar</p><h2>Every practice, game, and tournament.</h2><p className="muted">Coaches see the schedule for their assigned teams. Molly can keep every team updated here.</p></div><CalendarDays/></div><div className="calendar-tools"><select value={team} onChange={event=>setTeam(event.target.value)}><option value="all">All teams</option>{teams.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={type} onChange={event=>setType(event.target.value)}><option value="all">All event types</option><option value="practice">Practices</option><option value="game">Games</option><option value="tournament">Tournaments</option><option value="meeting">Meetings</option><option value="other">Other</option></select>{canManage?<><button className="calendar-template" onClick={()=>download("invictus-team-schedule-template.csv",template)}><Download/> Template</button><label className="calendar-import"><FileUp/> Import CSV<input type="file" accept=".csv,text/csv" onChange={readImport}/></label><button onClick={()=>setEditing(blank(teams[0]?.id??""))}><Plus/> Add event</button></>:null}</div><div className="calendar-days">{grouped.map(([dateValue,items])=><article key={dateValue}><h3>{day(`${dateValue}T12:00:00`)}</h3>{items.map(item=><button key={item.id} className={`calendar-event event-${item.eventType} status-${item.status}`} onClick={()=>canManage&&setEditing({...item,startAt:local(item.startAt),endAt:local(item.endAt)})}><span className="calendar-time"><Clock3/>{time(item.startAt)}{item.endAt?` – ${time(item.endAt)}`:""}</span><span><strong>{item.title}</strong><small>{item.teamName}{item.opponent?` vs. ${item.opponent}`:""}</small></span><span className="calendar-location"><MapPin/>{item.location||"Location TBD"}</span><b>{item.status}</b></button>)}</article>)}</div>{!grouped.length?<p className="clearance-empty">No upcoming team events have been added yet.</p>:null}{message?<p className="plan-message">{message}</p>:null}
    {imports?<div className="calendar-modal" onMouseDown={()=>setImports(null)}><div className="calendar-import-preview" onMouseDown={event=>event.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">Schedule import</p><h3>Review before importing</h3></div><button onClick={()=>setImports(null)}><X/></button></div><p className="muted">Team names must exactly match the teams already in Invictus Hub.</p><div className="table-wrap"><table><thead><tr><th>Row</th><th>Team</th><th>Event</th><th>Date / time</th><th>Result</th></tr></thead><tbody>{imports.map(item=><tr key={item.row} className={item.error?"import-error":""}><td>{item.row}</td><td>{item.teamName}</td><td><strong>{item.title}</strong><small>{item.eventType}</small></td><td>{item.startAt.replace("T"," ")}</td><td>{item.error||"Ready"}</td></tr>)}</tbody></table></div><div className="import-footer"><span>{imports.filter(item=>!item.error).length} ready · {imports.filter(item=>item.error).length} need correction</span><button className="secondary" onClick={importAll} disabled={saving||!imports.length||imports.some(item=>item.error)}><FileUp/>{saving?"Importing...":`Import ${imports.length} events`}</button></div>{message?<p className="plan-message">{message}</p>:null}</div></div>:null}
    {editing?<div className="calendar-modal" onMouseDown={()=>setEditing(null)}><div className="calendar-form" onMouseDown={event=>event.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">{editing.id?"Edit event":"New team event"}</p><h3>{editing.id?editing.title:"Add to the calendar"}</h3></div><button onClick={()=>setEditing(null)}><X/></button></div><div className="calendar-form-grid"><label>Team<select value={editing.teamId} onChange={event=>change("teamId",event.target.value)}><option value="">Choose...</option>{teams.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Type<select value={editing.eventType} onChange={event=>change("eventType",event.target.value)}><option value="practice">Practice</option><option value="game">Game</option><option value="tournament">Tournament</option><option value="meeting">Meeting</option><option value="other">Other</option></select></label><label className="calendar-wide">Event name<input value={editing.title} onChange={event=>change("title",event.target.value)} placeholder="Practice, league game, tournament..."/></label><label>Starts<input type="datetime-local" value={editing.startAt} onChange={event=>change("startAt",event.target.value)}/></label><label>Ends<input type="datetime-local" value={editing.endAt} onChange={event=>change("endAt",event.target.value)}/></label><label>Location<input value={editing.location} onChange={event=>change("location",event.target.value)}/></label><label>Opponent<input value={editing.opponent} onChange={event=>change("opponent",event.target.value)} placeholder="Games only"/></label><label>Arrive early (minutes)<input type="number" min="0" value={editing.arrivalMinutes||""} onChange={event=>change("arrivalMinutes",Number(event.target.value))}/></label><label>Status<select value={editing.status} onChange={event=>change("status",event.target.value)}><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="calendar-wide">Notes<textarea value={editing.notes} onChange={event=>change("notes",event.target.value)} placeholder="Uniform, parking, arrival instructions..."/></label></div><button className="secondary" onClick={save} disabled={saving}><Save/>{saving?"Saving...":"Save event"}</button>{message?<p className="plan-message">{message}</p>:null}</div></div>:null}</section>
}
